// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxslQcPKcQnod_RZ9cjZDkvCUQejICado',
    appId: '1:608113394957:web:5ea11fee5b61cea7f15c44',
    messagingSenderId: '608113394957',
    projectId: 'lessonauth-11f32',
    authDomain: 'lessonauth-11f32.firebaseapp.com',
    storageBucket: 'lessonauth-11f32.appspot.com',
    measurementId: 'G-1SP65NKN27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_39mUICTNzVxS80veyA7pOJQZ1gcwDUs',
    appId: '1:608113394957:android:0c5aa4d7d8cd9732f15c44',
    messagingSenderId: '608113394957',
    projectId: 'lessonauth-11f32',
    storageBucket: 'lessonauth-11f32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6oLIV0j9erLNVDyIq22iDeA_cyTxbCas',
    appId: '1:608113394957:ios:60f0fa3b123efdd9f15c44',
    messagingSenderId: '608113394957',
    projectId: 'lessonauth-11f32',
    storageBucket: 'lessonauth-11f32.appspot.com',
    iosBundleId: 'com.example.lesson6Lesson67July',
  );
}
